#!/bin/bash
###################################################################
# A Project of TNET Services, Inc
#
# Title:     rpi-wiggle
# Author:    Kevin Reed (Dweeber)
#            dweeber.dweebs@gmail.com
# Credits:   jojopi on Raspberry Pi Forum who provided sample code
#            
# Project:   Raspberry Pi Stuff
# Copyright: Released to the Public Domain
# Status:    THIS IS EXPERIMENTAL USE AT YOUR OWN RISK
#            THIS IS NOT A WORKING SCRIPT AT THIS TIME!
#
# Purpose:
# This is a simple script which looks at the current disk that is
# being used and expands the filesystem to almost the max 
# minus 3 512 blocks.  This is the ensure that the image is
# smaller than most SDcards of that size
#
# Instructions:
# Script needs to be run as root.  It is pretty much automatic... 
# it performs a resize command and setups a script which will 
# run after a reboot and then ask you to press enter to reboot.
#
# The script WILL REBOOT YOUR SYSTEM
#
# When the system is coming back up, the next command will run
# automatically, and the one time script will be removed and
# when you see the login prompt again, it will be complete
#
###################################################################
# START OF SCRIPT
###################################################################
PROGRAM="rpi-wiggle"
VERSION="v0.1 2012-09-14"
###################################################################
if [ $(id -u) -ne 0 ]; then
  printf "Script must be run as root. Try 'sudo wiggle'\n"
  exit 1
fi
###################################################################
DISK_SIZE="$(($(sudo blockdev --getsz /dev/mmcblk0)/2048/925))"
PART_START="$(sudo parted /dev/mmcblk0 -ms unit s p |grep "^2" |cut -f2 -d:)"
[ "$PART_START" ] || exit 1
PART_END="$(((DISK_SIZE*925*2048-1)-1024))"
###################################################################
# Display some Stuff...
###################################################################
echo $PROGRAM - $VERSION
echo ======================================================
echo Expand to SDCard Size with some wiggle room
echo This script will calculate the size of the current
echo SDcard, reset the size to max with some wiggle room
echo and then reboot to complete the task.
echo
echo This should ONLY be run ONCE!
echo 
echo 
echo Current Disk Info
fdisk -l /dev/mmcblk0
echo
echo ======================================================
echo
echo Calculated Info:
echo " Disk Size  = $DISK_SIZE gb"
echo " Part Start = $PART_START"
echo " Part End   = $PART_END"
echo
echo "Making changes using fdisk..."
printf "d\n2\nn\np\n2\n$PART_START\n$PART_END\np\nw\n" | fdisk /dev/mmcblk0
echo

# now set up an init.d script
# example stolen from raspi-config script

cat <<\EOF > /etc/init.d/resize2fs_once &&
#!/bin/sh
### BEGIN INIT INFO
# Provides:          resize2fs_once
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5 S
# Default-Stop:
# Short-Description: Test for one time run on boot
# Description:
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Starting resize2fs_once, THIS WILL TAKE A FEW MINUTES " && 
    
    # Do our stuff....   
	resize2fs /dev/mmcblk0p2 &&
	
    # Okay, not lets remove this script
    rm /etc/init.d/resize2fs_once &&
    update-rc.d resize2fs_once remove &&
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
EOF
  chmod +x /etc/init.d/resize2fs_once &&
  update-rc.d resize2fs_once defaults &&

echo
echo System is now ready to resize your system.  A REBOOT IS REQUIRED NOW!
echo "Press ENTER to reboot : \c"
read aok
echo REBOOTING....
/bin/sync
/sbin/reboot
echo
echo Script Complete...

###################################################################
# END OF SCRIPT
###################################################################
